add endpoint recipe to favorite
TOP10-ms-students/Foodies-Back pull request #11
Opened 2024-09-05 11:08 UTC by YagovkinDmytro

2024-09-06 11:02 UTC, ICxodnik requested changes

2024-09-06 17:01 UTC, YagovkinDmytro commented on services/recipesServices.js
> +        where: { recipeId },
добавил проверку, сейчас все работает

2024-09-06 21:06 UTC, roman-zubach requested changes

2024-09-07 08:56 UTC, YagovkinDmytro commented on services/recipesServices.js
> +const addFavoriteRecipe = async data => {
так, змінив назву функції

2024-09-10 11:55 UTC, merged