add endpoint updating the avatar
TOP10-ms-students/Foodies-Back pull request #16
Opened 2024-09-05 14:46 UTC by YagovkinDmytro

2024-09-06 20:25 UTC, roman-zubach requested changes

2024-09-06 20:25 UTC, roman-zubach commented on helpers/getAvatarPath.js
> +export const getAvatarPath = async data => {
здається ми повинні використовувати `cloudinary`

2024-09-06 20:25 UTC, roman-zubach commented on services/usersServices.js
> +        return user.update(data,{
в метод `updateUser` прокидай відразу обєкт юзера, він в тебе є.

2024-09-06 20:25 UTC, roman-zubach commented on services/usersServices.js
> +        if (avatarExtension === "jpg") {
дуже цікава умова, як на рахунок інших розширень?

2024-09-07 16:49 UTC, YagovkinDmytro commented on services/usersServices.js
> +        if (avatarExtension === "jpg") {
додав розширення, дякую

2024-09-10 11:55 UTC, merged